----> TEST: test_example_1

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
test_example_1 is a Catch v2.13.10 host application.
Run with -? for options

-------------------------------------------------------------------------------
TEST 1
-------------------------------------------------------------------------------
test_example_1.cpp:5
...............................................................................

test_example_1.cpp:7: FAILED:
  CHECK( multiplyOdd(1) == 1 )
with expansion:
  0 == 1

test_example_1.cpp:8: FAILED:
  CHECK( multiplyOdd(456789) == 315 )
with expansion:
  0 == 315 (0x13b)

test_example_1.cpp:9: FAILED:
  CHECK( multiplyOdd(123) == 3 )
with expansion:
  0 == 3

===============================================================================
test cases: 1 | 1 failed
assertions: 5 | 2 passed | 3 failed



----> TEST: test_example_2

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
test_example_2 is a Catch v2.13.10 host application.
Run with -? for options

-------------------------------------------------------------------------------
TEST 2
-------------------------------------------------------------------------------
test_example_2.cpp:5
...............................................................................

test_example_2.cpp:7: FAILED:
  CHECK( multiplyOdd(1) == 1 )
with expansion:
  0 == 1

test_example_2.cpp:8: FAILED:
  CHECK( multiplyOdd(456789) == 315 )
with expansion:
  0 == 315 (0x13b)

test_example_2.cpp:9: FAILED:
  CHECK( multiplyOdd(123) == 3 )
with expansion:
  0 == 3

===============================================================================
test cases: 1 | 1 failed
assertions: 3 | 3 failed



